development:
  adapter: postgresql
  encoding: unicode
  database: local_chat_app
  pool: 5
  username: user
  password: user1234

production:
  adapter: postgresql
  encoding: unicode
  database: chd_production_demo
  pool: 5
  #port: 5433
  username: deploy
  password: jason@myridz


